version: '3.8'
volumes:
  db:
services:
  gateway:
    build: gateway/.
    image: shareit-gateway-image
    container_name: shareit-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - db
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090
      - JAVA_OPTS=-Xmx512m -Xms256m

  server:
    build: server/.
    image: shareit-server-image
    container_name: shareit-server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - SPRING_DATASOURCE_USERNAME=shareit
      - SPRING_DATASOURCE_PASSWORD=shareit
      - JAVA_OPTS=-Xmx512m -Xms256m

  db:
    # образ, из которого должен быть запущен контейнер
    image: postgres:13.7-alpine
    container_name: shareit_db
    ports:
      - "6541:5432"
    # volume и связанная с ним директория в контейнере
    volumes:
      - db:/var/lib/postgresql/data/
    # переменные окружения
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=shareit
      - POSTGRES_PASSWORD=shareit
