DROP TABLE IF EXISTS items;
DROP TABLE IF EXISTS users;
-- DROP TABLE IF EXISTS tags;
-- DROP TABLE IF EXISTS item_notes;

CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS items (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(1000) NOT NULL,
    is_available BOOLEAN NOT NULL,
    user_id BIGINT,
    CONSTRAINT fk_items_to_users FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- CREATE TABLE IF NOT EXISTS tags (
--     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     item_id BIGINT,
--     name VARCHAR(50),
--     CONSTRAINT fk_tags_to_items FOREIGN KEY(item_id)
--     REFERENCES items(id)
-- );
--
-- CREATE TABLE IF NOT EXISTS item_notes (
--     id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
--     item_id BIGINT,
--     text VARCHAR(1000),
--     note_date timestamp,
--     CONSTRAINT items FOREIGN KEY(item_id)
--     REFERENCES items(id)
-- );

-- CREATE TABLE IF NOT EXISTS film_x_genre (
--   film_id integer REFERENCES film (film_id) ON DELETE CASCADE ON UPDATE CASCADE,
--   genre_id integer REFERENCES genre (genre_id),
--   PRIMARY KEY (film_id, genre_id)
-- );